@extends('en.layout.mainlayout')
@section('aboveContent')
<div class="container-fluid about px-0">
  <div class="container p-5">
    <h2 class="h1-responsivefooter text-center my-4">About us</h2>
    <div class="row">
      <p>Xiangqi (Chinese: 象棋; pinyin: xiàngqí; English: /ˈʃɑːŋtʃi/), also called Chinese chess, is a strategy board game for two players. It is one of the most popular board games in China, and is in the same family as Western (or international) chess, chaturanga, shogi, Indian chess and janggi. Besides China and areas with significant ethnic Chinese communities, xiangqi is also a popular pastime in Vietnam, where it is known as cờ tướng.</p>
      <p>The game represents a battle between two armies, with the object of capturing the enemy's general (king). Distinctive features of xiangqi include the cannon (pao), which must jump to capture; a rule prohibiting the generals from facing each other directly; areas on the board called the river and palace, which restrict the movement of some pieces (but enhance that of others); and placement of the pieces on the intersections of the board lines, rather than within the squares.</p>
      <h3 class="w-100">Board</h3>
      <p>Xiangqi is played on a board nine lines wide and ten lines long. As in the game Go (Wéiqí 圍棋/围棋), the pieces are placed on the intersections, which are known as points. The vertical lines are known as files (Chinese: 路; pinyin: lù; "road"), and the horizontal lines are known as ranks (traditional Chinese: 線; simplified Chinese: 线; pinyin: xiàn; "line").</p>
      <p>Centred at the first to third and eighth to tenth ranks of the board are two zones, each three points by three points, demarcated by two diagonal lines connecting opposite corners and intersecting at the centre point. Each of these areas is known as 宮/宫 gōng, a castle.</p>
      <p>Dividing the two opposing sides, between the fifth and sixth ranks, is 河 hé, the "river". The river is often marked with the phrases 楚河 chǔ hé, meaning "River of the Chu ", and 漢界 (in Traditional Chinese), hàn jiè, meaning "Border of the Han", a reference to the Chu–Han War. Although the river provides a visual division between the two sides, only two pieces are affected by its presence: soldiers have an enhanced move after crossing the river, and elephants cannot cross it. The starting points of the soldiers and cannons are usually, but not always, marked with small crosses.</p>
      <h3 class="w-100">Rules</h3>
      <p>The pieces start in the position shown in the diagram above. Which player moves first has varied throughout history and from one part of China to another. Different xiangqi books advise either that the black or red side moves first.[citation needed] Some books refer to the two sides as north and south; which direction corresponds to which colour also varies from source to source. Generally, Red moves first in most modern tournaments.</p>
      <p>Each player in turn moves one piece from the point it occupies, to another point. Pieces are generally not permitted to move through a point occupied by another piece. A piece can be moved onto a point occupied by an enemy piece, in which case the enemy piece is captured and removed from the board. A player cannot capture one of his own pieces. Pieces are never promoted (converted into other pieces), although the soldier is able to move sideways after it crosses the river. Almost all pieces capture using their normal moves, while the cannon has a special capture move described below.</p>
      <p>The game ends when one player captures the other's general. When the general is in danger of being captured by the enemy player on his next move, the enemy player has "delivered a check" (simplified Chinese: 照将/将军; traditional Chinese: 照將/將軍, abbreviated (simplified Chinese: 将; traditional Chinese: 將; pinyin: jiāngjiāng)), and the general is "in check". A check should be announced. If the general's player can make no move to prevent the general's capture, the situation is called "checkmate" (simplified Chinese: 将死; traditional Chinese: 將死). Unlike in chess, in which stalemate is a draw, in xiangqi, it is a loss for the stalemated player.</p>
      <p>In xiangqi, a player—often with a material or positional disadvantage—may attempt to check or chase pieces in a way such that the moves fall in a cycle, forcing the opponent to draw the game. The following special rules are used to make it harder to draw the game by endless checking or chasing, regardless of whether the positions of the pieces are repeated or not:</p>
      <ul>
        <li>A player making perpetual checks with one piece or several pieces can be ruled to have lost unless he or she stops such checking.</li>
        <li>A player who perpetually chases any one unprotected piece with one or more pieces, excluding generals and soldiers, will be ruled to have lost unless he or she stops such chasing.</li>
        <li>If one side perpetually checks and the other side perpetually chases, the checking side has to stop or be ruled to have lost.</li>
        <li>When neither side violates the rules and both persist in not making an alternate move, the game can be ruled as a draw.</li>
        <li>When both sides violate the same rule at the same time and both persist in not making an alternate move, the game can be ruled as a draw.</li>
      </ul>
      <p>Different sets of rules set different limits on what is considered perpetual. For example, club xiangqi rules allow a player to check or chase six consecutive times using one piece, twelve times using two pieces, and eighteen times using three pieces before considering the action perpetual.</p>
      <p>The above rules to prevent perpetual checking and chasing, while popular, are not the only ones; there are numerous end game situations.</p>
      <h3 class="w-100">Pieces</h3>
      <p>Each player controls an army of 16 pieces; the armies are usually coloured red and black. Pieces are flat circular disks labeled or engraved with a Chinese character identifying the piece type, and in a colour indicating which player has ownership. The black pieces are marked with somewhat different characters from the corresponding red pieces.</p>
      <p>In mainland China, most sets still use traditional Chinese characters (as opposed to simplified Chinese characters). Modern pieces are usually plastic, though some sets are wooden, and more expensive sets may use jade. In more ancient times, many sets were simple unpainted woodcarvings; thus, to distinguish between pieces of the two sides, most corresponding pieces used characters that were similar but varied slightly. This practice may have originated in situations where there was only one material available to make the pieces from and no colouring material available to distinguish the opposing armies. The oldest xiangqi piece found to date is a 俥 (chariot) piece. It is kept in the Henan Provincial Museum.</p>
      <h4 class="w-100">General</h4>
      <p>Generals (or kings) are labelled 將 (trad.) / 将 (simp.) jiàng ("general") on the black side and 帥 (trad.) / 帅 (simp.) shuài ("marshal") on the red side.</p>
      <p>The general starts the game at the midpoint of the back edge, within the palace. The general may move and capture one point orthogonally and may not leave the palace, with the following exception.</p>
      <p>The two generals may not face each other along the same file with no intervening pieces. If that happens, the 飛將 ("flying general") move may be executed, in which the general to move may cross the board to capture the enemy general. In practice, this rule means that creating this situation in the first place means moving into check, and is therefore not allowed.</p>
      <p>The Indian name king for this piece was changed to general because of Chinese naming taboos; China's rulers objected to their royal titles being given to game pieces.</p>
      <h4 class="w-100">Advisor</h4>
      <p>Advisors (also known as guards or ministers, and less commonly as assistants, mandarins, or warriors) are labelled 士 shì ("scholar", "gentleman", "officer", "guardian") for Black and 仕 shì ("scholar", "official", "guardian") for Red. Rarely, sets use the character 士 for both colours.</p>
      <p>The advisors start on either side of the general. They move and capture one point diagonally and may not leave the palace, which confines them to five points on the board. The advisor is probably derived from the mantri in chaturanga, like the queen in Western chess.</p>
      <p>There is some controversy about whether "士" really is intended to mean "scholar", "gentleman" which would be "士人", or "guard", "guardian" which would be "衛士" (simplified Chinese: 卫士). To some, the latter seems more plausible because their functionality seems to be to guard/protect the general. The common Western translation "advisor" does not reflect this layer of meaning.</p>
      <h4 class="w-100">Elephant</h4>
      <p>Elephants (or bishops) are labeled 象 xiàng ("elephant") for Black and 相 xiàng ("minister") for Red. They are located next to the advisors. These pieces move and capture exactly two points diagonally and may not jump over intervening pieces; the move is described as being like the character 田 Tián ("field"). If an elephant cannot move due to a diagonally adjacent piece, it is known as "blocking the elephant's eye" (塞象眼).</p>
      <p>Elephants may not cross the river, and serve as defensive pieces. Because an elephant's movement is restricted to just seven board positions, it can be easily trapped or threatened. The two elephants are often used to defend each other.</p>
      <p>The Chinese characters for "minister" and "elephant" are homophones in Mandarin and both have alternative meanings as "appearance" or "image". However, in English, both are referred to as elephants.</p>
      <h4 class="w-100">Horse</h4>
      <p>Horses (or knights) are labelled 馬 mǎ for Black and 傌 mǎ for Red in sets marked with Traditional Chinese characters and 马 mǎ for both Black and Red in sets marked with Simplified Chinese characters. Some traditional sets use 馬 for both colours. Horses begin the game next to the elephants, on their outside flanks. A horse moves and captures one point orthogonally and then one point diagonally away from its former position, a move which is traditionally described as being like the character 日 Rì. The horse does not jump as the knight does in Western chess, and can be blocked by a piece located one point horizontally or vertically adjacent to it. Blocking a horse is called "hobbling the horse's leg" (蹩馬腿). The diagram on the left illustrates the horse's movement.</p>
      <p>Since horses can be blocked, it is sometimes possible to trap the opponent's horse. It is possible for one player's horse to have an asymmetric attack advantage if an opponent's horse is blocked, as seen in the diagram on the right.</p>
      <h4 class="w-100">Chariot</h4>
      <p>Chariots (or rooks) are labelled 車 jū for Black and 俥 jū for Red in sets marked with Traditional Chinese characters and 车 for both Black and Red in sets marked with Simplified Chinese characters. Some traditional sets use 車 for both colours. In the context of Chinese Chess, all of these characters are pronounced as jū (instead of the common pronunciation chē). The chariot moves and captures any distance orthogonally, but may not jump over intervening pieces. The chariots begin the game on the points at the corners of the board. The chariot is often considered to be the strongest piece in the game due to its freedom of movement and lack of restrictions.</p>
      <p>The chariot is sometimes known as the rook by English-speaking players, since it is like the rook in Western chess. Chinese players (and others) often call this piece a car, since that is one modern meaning of the character 車.</p>
      <h4 class="w-100">Cannon</h4>
      <p>Cannons are labelled 砲 pào ("catapult") for Black and 炮 pào ("cannon") for Red. The names are homophones, though sometimes 炮 is used for both Red and Black. The 石 shí radical of 砲 means "stone", and the 火 huǒ radical of 炮 means "fire". Both colours' pieces are normally referred to as cannons in English. The black piece is sometimes labelled 包.</p>
      <p>Each player has two cannons, which start on the row behind the soldiers, two points in front of the horses. Cannons move like chariots, any distance orthogonally without jumping, but can only capture by jumping a single piece, friend or foe, along the path of attack. The piece over which the cannon jumps is called the 炮臺 (trad.) / 炮台 (simp.) pào tái ("cannon platform" or "screen"). Any number of unoccupied spaces, including none, may exist between the cannon, screen, and the piece to be captured. Cannons can be exchanged for horses immediately from their starting positions.</p>
      <h4 class="w-100">Soldier</h4>
      <p>Soldiers are labelled 卒 zú ("pawn" or "private") for Black and 兵 bīng ("soldier") for Red. Each side starts with five soldiers. Soldiers begin the game located on every other point one row back from the edge of the river. They move and capture by advancing one point. Once they have crossed the river, they may also move and capture one point horizontally. Soldiers cannot move backward, and therefore cannot retreat; after advancing to the last rank of the board, however, a soldier may still move sideways at the enemy's edge. The soldier is sometimes called the "pawn" by English-speaking players, due to the pieces' similarities.</p>
    </div>
  </div>
</div>
@endsection
@section('belowContent')
@endsection